### ISSUE TITLE
Warning: Trying to access array offset on value of type bool in AdminLinksInFrontend.module on line 169

### ISSUE THREAD

**Issue by MoritzLost** [horst-n/AdminLinksInFrontend#2]
I'm getting a warning on a system where OP Cache is disabled due to the following lines:

```php
$opc = opcache_get_status();
self::$opcEnabled = $opc['opcache_enabled'];
```

[AdminLinksInFrontend.module#L168-L169](https://github.com/horst-n/AdminLinksInFrontend/blob/a66819109e94721119f70e7c81c3b1d68d3bd290/AdminLinksInFrontend.module#L168-L169)

According to the documentation, [opcache_get_status](https://www.php.net/manual/en/function.opcache-get-status.php) returns boolean `false` if OP Cache is disabled, so the array access is causing the warning in this situation.

Should be a simple fix, maybe something like this:

```php
$opc = opcache_get_status();
self::$opcEnabled = $opc && $opc['opcache_enabled'];
```

**Comment by horst-n** [comment]
Thank you! @MoritzLost
